human: True

batch_size: 256
max_iter: 20000
lr: 0.001
lr_min: 0.0001
log_every: 10
val_every: 1000
val_num: 10
save_every: 5000
grad_clip: 10.0

test_grasp_num: 20
test_topk: 20

model:
  name: HierarchicalModel
  backbone:
    name: WrappedMinkUNet
    out_feat_dim: 1024
    voxel_size: 0.005
  grasp_type_emb:
    name: LearnableTypeCond
    in_feat_dim: ${..backbone.out_feat_dim}
    out_feat_dim: 128
    use_predictor: false
    disabled: false
  head:
    name: DiffusionBiRT_v2
    in_feat_dim:
    diffusion:
      ode: 1
      scheduler_type: DDIMScheduler
      scheduler:
        beta_schedule: squaredcos_cap_v2
        prediction_type: v_prediction
        num_train_timesteps: 128
        clip_sample: False
      num_inference_timesteps: 10
      log_prob_type: accurate_cont
      loss_type: l1

loss_weight:
  loss_diffusion: 1.0
  loss_type: 1.0
